-- MySQL Script generated by MySQL Workbench
-- 05/22/16 15:49:36
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema plagiarism
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `plagiarism` ;

-- -----------------------------------------------------
-- Schema plagiarism
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `plagiarism` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema plagiarism
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `plagiarism` ;

-- -----------------------------------------------------
-- Schema plagiarism
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `plagiarism` DEFAULT CHARACTER SET utf8 ;
USE `plagiarism` ;

-- -----------------------------------------------------
-- Table `plagiarism`.`source_doc`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `plagiarism`.`source_doc` ;

CREATE TABLE IF NOT EXISTS `plagiarism`.`source_doc` (
  `source_doc_id` INT NOT NULL AUTO_INCREMENT,
  `source_doc_text` TEXT NULL,
  `source_doc_name` VARCHAR(45) NULL,
  PRIMARY KEY (`source_doc_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `plagiarism`.`suspiciuos_doc`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `plagiarism`.`suspiciuos_doc` ;

CREATE TABLE IF NOT EXISTS `plagiarism`.`suspiciuos_doc` (
  `suspiciuos_doc_id` INT NOT NULL AUTO_INCREMENT,
  `suspiciuos_doc_text` TEXT NULL,
  `suspiciuos_doc_name` VARCHAR(45) NULL,
  PRIMARY KEY (`suspiciuos_doc_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `plagiarism`.`annotation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `plagiarism`.`annotation` ;

CREATE TABLE IF NOT EXISTS `plagiarism`.`annotation` (
  `annotation_id` INT NOT NULL AUTO_INCREMENT,
  `source_offset` MEDIUMTEXT NULL,
  `source_length` MEDIUMTEXT NULL,
  `suspicious_offset` MEDIUMTEXT NULL,
  `suspiciuos_length` MEDIUMTEXT NULL,
  `obfuscation` VARCHAR(45) NULL,
  `type` VARCHAR(45) NULL,
  `source_doc_id` INT NULL,
  `suspicious_doc_id` INT NOT NULL,
  PRIMARY KEY (`annotation_id`),
  INDEX `fk_annotation_source_doc_idx` (`source_doc_id` ASC),
  INDEX `fk_annotation_suspicious_doc1_idx` (`suspicious_doc_id` ASC),
  CONSTRAINT `fk_annotation_source_doc`
    FOREIGN KEY (`source_doc_id`)
    REFERENCES `plagiarism`.`source_doc` (`source_doc_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_annotation_suspicious_doc1`
    FOREIGN KEY (`suspicious_doc_id`)
    REFERENCES `plagiarism`.`suspiciuos_doc` (`suspiciuos_doc_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `plagiarism` ;

-- -----------------------------------------------------
-- Table `plagiarism`.`phrase`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `plagiarism`.`phrase` ;

CREATE TABLE IF NOT EXISTS `plagiarism`.`phrase` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `pathname` VARCHAR(200) NULL DEFAULT NULL,
  `filename` VARCHAR(200) NULL DEFAULT NULL,
  `original` TEXT NULL DEFAULT NULL,
  `tokens` TEXT NULL,
  `source_doc_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_phrase_source_doc1_idx` (`source_doc_id` ASC),
  CONSTRAINT `fk_phrase_source_doc1`
    FOREIGN KEY (`source_doc_id`)
    REFERENCES `plagiarism`.`source_doc` (`source_doc_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `plagiarism`.`testphrase`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `plagiarism`.`testphrase` ;

CREATE TABLE IF NOT EXISTS `plagiarism`.`testphrase` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `filename` VARCHAR(200) NULL DEFAULT NULL,
  `pathname` VARCHAR(200) NULL DEFAULT NULL,
  `phrase` VARCHAR(200) NULL DEFAULT NULL,
  `suspicious_doc_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_testphrase_suspicious_doc1_idx` (`suspicious_doc_id` ASC),
  CONSTRAINT `fk_testphrase_suspicious_doc1`
    FOREIGN KEY (`suspiciuos_doc_id`)
    REFERENCES `plagiarism`.`suspiciuos_doc` (`suspiciuos_doc_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `plagiarism`.`assoc`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `plagiarism`.`assoc` ;

CREATE TABLE IF NOT EXISTS `plagiarism`.`assoc` (
  `assoc_id` INT(11) NOT NULL AUTO_INCREMENT,
  `score` DOUBLE NULL DEFAULT NULL,
  `phrase_id` INT(11) NOT NULL,
  `testphrase_id` INT(11) NOT NULL,
  PRIMARY KEY (`assoc_id`),
  INDEX `fk_assoc_phrase1_idx` (`phrase_id` ASC),
  INDEX `fk_assoc_testphrase1_idx` (`testphrase_id` ASC),
  CONSTRAINT `fk_assoc_phrase1`
    FOREIGN KEY (`phrase_id`)
    REFERENCES `plagiarism`.`phrase` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_assoc_testphrase1`
    FOREIGN KEY (`testphrase_id`)
    REFERENCES `plagiarism`.`testphrase` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
