
package plagiarism.util.pojos;

import java.io.Serializable;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * <h2>Association POJO</h2>
 * 
 * <p>This class is a POJO representing an entity in the database generated by
 * NetBeans' Hibernate plugin</p>
 *
 * @author Ali Wassouf
 * @version 1.0
 * @since 2016-04-10
 */
@Entity
@Table(name = "ASSOC")
public class Assoc implements Serializable {

    private int assoc_id;
    private Phrase phrase;
    private TestPhrase testphrase;

    private Double score;

    /**
     * The default constructor of the Association object
     */
    public Assoc() {
    }

    /**
     * Overloaded constructor that takes parameters to be set
     * 
     * @param assoc_id the <b>id</b> attribute of the Association table
     * @param phrase the <b>phrase</b> attribute of the Association table 
     * @param testphrase the <b>testphrase</b> attribute of the Association table 
     * @param score the <b>score</b> attribute of the Association table.
     */
    public Assoc(int assoc_id, Phrase phrase, TestPhrase testphrase, Double score) {
        this.assoc_id = assoc_id;
        this.phrase = phrase;
        this.testphrase = testphrase;
        this.score = score;
    }

    /**
     * Overloaded constructor that takes parameters to be set.
     * Does not need an <b>id</b> parameter.
     * @param phrase the <b>phrase</b> attribute of the Association table 
     * @param testphrase the <b>testphrase</b> attribute of the Association table 
     * @param score the <b>score</b> attribute of the Association table.
     */
    public Assoc( Phrase phrase, TestPhrase testphrase, Double score) {
        
        this.phrase = phrase;
        this.testphrase = testphrase;
        this.score = score;
    }
    /**
     * The getter method of the <b>id</b> of the Association table.
     * @return int assoc_id
     */
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "ASSOC_ID", nullable = false, unique = true)
    public int getAssoc_id() {
        return assoc_id;
    }

    /**
     * This method is the setter of the Association <b>id</b>. It is auto generated.
     * 
     * @param assoc_id the <b>id</b> value to be set
     */
    public void setAssoc_id(int assoc_id) {
        this.assoc_id = assoc_id;
    }

     /**
     * This method is the getter of the Association's attribute: <b>phrase</b>. It is auto generated.
     * 
     * @return Phrase phrase
     */
    @ManyToOne(cascade = CascadeType.ALL)
    @JoinColumn(name = "PHRASE_ID")
    public Phrase getPhrase() {
        return phrase;
    }

    /**
     * This is the setter method of the <b>phrase</b> attribute of the Association.
     * It is auto generated.
     * 
     * @param phrase
     */
    public void setPhrase(Phrase phrase) {
        this.phrase = phrase;
    }

    /**
     * The getter method of the <b>testphrase</b> attribute of the Association table.
     * @return TestPhrase testphrase 
     */
    @ManyToOne(cascade = CascadeType.ALL)
    @JoinColumn(name = "TESTPHRASE_ID")
    public TestPhrase getTestphrase() {
        return testphrase;
    }

    /**
     * The setter method of the <b>testphrase</b> attribute of the Association table.
     * @param testphrase
     */
    public void setTestphrase(TestPhrase testphrase) {
        this.testphrase = testphrase;
    }

    /**
     * the getter of the <b>score</b> attribute of the Association table.
     * @return Double <b>score</b>
     */
    @Column(name = "SCORE")
    public Double getScore() {
        return score;
    }

    /**
     * the setter method of the <b>score</b> attribute of the Association table.
     * @param score
     */
    public void setScore(Double score) {
        this.score = score;
    }

}
