/*
 * This class is an entity class generated by NetBeans's Hibernate plugin.
 * It represents a table in the database. Phrase table.
 */
package plagiarism.util.pojos;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * <h2>Phrase POJO</h2>
 * <p>
 * This class is a POJO representing an entity in the database generated by
 * NetBeans' Hibernate plugin</p>
 *
 * @author Ali Wassouf
 * @version 1.0
 * @since 2016-04-10
 */
@Entity
@Table(name = "PHRASE")
public class Phrase implements Serializable {

    private int id;
    private String pathname;
    private String filename;
    private String original;
    private String tokens;

    private Set<Assoc> associations = new HashSet<Assoc>(0);

    /**
     * Default constructor.
     */
    public Phrase() {
    }

    /**
     * Overloaded constructor with parameters. Does not take <b>id</b>
     * parameter.
     *
     * @param pathname the path where the file containing the phrase is located
     * @param filename the file containing the phrase.
     * @param original the phrase as it was extracted from the file.
     * @param tokens the tokens contained in the phrase.
     */
    public Phrase(String pathname, String filename, String original, String tokens) {

        this.pathname = pathname;
        this.filename = filename;
        this.original = original;
        this.tokens = tokens;
    }

    /**
     * Overloaded constructor with parameters.
     *
     * @param id
     * @param pathname the path where the file containing the phrase is located
     * @param filename the file containing the phrase.
     * @param original the phrase as it was extracted from the file.
     * @param tokens the tokens contained in the phrase.
     */
    public Phrase(int id, String pathname, String filename, String original, String tokens) {
        this.id = id;
        this.pathname = pathname;
        this.filename = filename;
        this.original = original;
        this.tokens = tokens;
    }

    /**
     * Adds an Association instance to the Set of Associations
     *
     * @param assoc instance of type Association
     */
    public void addAssociation(Assoc assoc) {
        this.associations.add(assoc);
    }

    /**
     * Setter for the <b>id</b> parameter.
     *
     * @param id
     */
    public void setId(int id) {
        this.id = id;
    }

    /**
     * Setter for the <b>pathname</b> parameter.
     *
     * @param pathname
     */
    public void setPathname(String pathname) {
        this.pathname = pathname;
    }

    /**
     * Setter of the <b>filename</b> parameter.
     *
     * @param filename
     */
    public void setFilename(String filename) {
        this.filename = filename;
    }

    /**
     * Setter of the <b>original</b> parameter.
     *
     * @param original
     */
    public void setOriginal(String original) {
        this.original = original;
    }

    /**
     * Setter of the <b>tokens</b> parameter.
     *
     * @param tokens
     */
    public void setTokens(String tokens) {
        this.tokens = tokens;
    }

    /**
     * Setter of the <b>associations</b> parameter which represent a set of
     * Association instances.
     *
     * @param associations
     */
    public void setAssociations(Set<Assoc> associations) {
        this.associations = associations;
    }

    /**
     * Getter of the <b>id</b> parameter
     *
     * @return int id
     */
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "ID", nullable = false, unique = true)
    public int getId() {
        return id;
    }

    /**
     * Getter of the <b>pathname</b> parameter
     *
     * @return String pathname.
     */
    @Column(name = "PATHNAME")
    public String getPathname() {
        return pathname;
    }

    /**
     * Getter of the <b>filename</b> parameter
     *
     * @return String filename.
     */
    @Column(name = "FILENAME")
    public String getFilename() {
        return filename;
    }

    /**
     * Getter of the <b>original</b> parameter
     *
     * @return String original
     */
    @Column(name = "ORIGINAL")
    public String getOriginal() {
        return original;
    }

    /**
     * Getter of the <b>tokens</b> parameter
     *
     * @return String original
     */
    @Column(name = "TOKENS")
    public String getTokens() {
        return tokens;
    }

    /**
     * Getter of the <b>associations</b> parameter
     *
     * @return Set of Assoc associations
     */
    @OneToMany(mappedBy = "phrase")
    public Set<Assoc> getAssociations() {
        return associations;
    }

}
