/*
 * This class is an entity class generated by NetBeans's Hibernate plugin.
 * It represents a table in the database. Phrase table.
 */
package plagiarism.util.pojos;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * <h2>Phrase POJO</h2>
 * <p>This class is a POJO representing an entity in the database generated by
 * NetBeans' Hibernate plugin</p>
 * @author Ali Wassouf
 * @version 1.0
 * @since 2016-04-10
 */
@Entity
@Table(name = "PHRASE")
public class Phrase implements Serializable {

    private int id;
    private String pathname;
    private String filename;
    private String original;
    private String tokens;

    private Set<Assoc> associations = new HashSet<Assoc>(0);

    /**
     * Default constructor.
     */
    public Phrase() {
    }

    /**
     * Overloaded constructor with parameters 
     * @param pathname the path where 
     * @param filename
     * @param original
     * @param tokens
     */
    public Phrase( String pathname, String filename, String original, String tokens) {
        
        this.pathname = pathname;
        this.filename = filename;
        this.original = original;
        this.tokens = tokens;
    }

    /**
     *
     * @param id
     * @param pathname
     * @param filename
     * @param original
     * @param tokens
     */
    public Phrase(int id, String pathname, String filename, String original, String tokens) {
        this.id = id;
        this.pathname = pathname;
        this.filename = filename;
        this.original = original;
        this.tokens = tokens;
    }

    
    /**
     *
     * @param assoc
     */
    public void addAssociation(Assoc assoc) {
        this.associations.add(assoc);
    }

    /**
     *
     * @param id
     */
    public void setId(int id) {
        this.id = id;
    }

    /**
     *
     * @param pathname
     */
    public void setPathname(String pathname) {
        this.pathname = pathname;
    }

    /**
     *
     * @param filename
     */
    public void setFilename(String filename) {
        this.filename = filename;
    }

    /**
     *
     * @param original
     */
    public void setOriginal(String original) {
        this.original = original;
    }

    /**
     *
     * @param tokens
     */
    public void setTokens(String tokens) {
        this.tokens = tokens;
    }

    /**
     *
     * @param associations
     */
    public void setAssociations(Set<Assoc> associations) {
        this.associations = associations;
    }

    /**
     *
     * @return
     */
    @Id
    @GeneratedValue(strategy= GenerationType.AUTO)
    @Column(name = "ID",nullable = false, unique=true)
    public int getId() {
        return id;
    }

    /**
     *
     * @return
     */
    @Column(name = "PATHNAME")
    public String getPathname() {
        return pathname;
    }

    /**
     *
     * @return
     */
    @Column(name = "FILENAME")
    public String getFilename() {
        return filename;
    }

    /**
     *
     * @return
     */
    @Column(name = "ORIGINAL")
    public String getOriginal() {
        return original;
    }

    /**
     *
     * @return
     */
    @Column(name = "TOKENS")
    public String getTokens() {
        return tokens;
    }

    /**
     *
     * @return
     */
    @OneToMany(mappedBy = "phrase")
    public Set<Assoc> getAssociations() {
        return associations;
    }

}
