/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package plagiarism.util.pojos;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * <h2>Source Document POJO</h2>
 * <p>
 * This class is a POJO representing an entity in the database generated by
 * NetBeans' Hibernate plugin</p>
 *
 * @author Ali Wassouf
 * @version 1.0
 * @since 2016-04-10
 */
@Entity
@Table(name = "source_doc")
public class Source_doc implements Serializable{
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "source_doc_id", nullable = false, unique = true)
    private int source_doc_id;

    @Column(name = "source_doc_text")
    private String source_doc_text;

    @Column(name = "source_doc_name")
    private String source_doc_name;

    @OneToMany(fetch = FetchType.EAGER,cascade = {CascadeType.PERSIST, CascadeType.MERGE, CascadeType.REFRESH}, mappedBy = "source_doc")
    private Set<Phrase> phrases = new HashSet<Phrase>(0);
    
    @OneToMany(cascade = CascadeType.ALL, mappedBy = "source_doc")
    private Set<Annotation> annotations = new HashSet<Annotation>(0);

    @OneToMany(cascade = CascadeType.ALL, mappedBy = "source_doc")
    private Set<CandidateDocs> candidateDocs = new HashSet<>(0);

    public Set<CandidateDocs> getCandidateDocs() {
        return candidateDocs;
    }

    public void setCandidateDocs(Set<CandidateDocs> candidateDocs) {
        this.candidateDocs = candidateDocs;
    }
    
    public Source_doc() {
    }

    public Source_doc(String source_doc_text, String source_doc_name) {
        this.source_doc_text = source_doc_text;
        this.source_doc_name = source_doc_name;
    }

    public int getSource_doc_id() {
        return source_doc_id;
    }

    public void setSource_doc_id(int source_doc_id) {
        this.source_doc_id = source_doc_id;
    }

    public String getSource_doc_text() {
        return source_doc_text;
    }

    public void setSource_doc_text(String source_doc_text) {
        this.source_doc_text = source_doc_text;
    }

    public String getSource_doc_name() {
        return source_doc_name;
    }

    public void setSource_doc_name(String source_doc_name) {
        this.source_doc_name = source_doc_name;
    }

    public Set<Phrase> getPhrases() {
        return phrases;
    }

    public void setPhrases(Set<Phrase> phrases) {
        this.phrases = phrases;
    }

    public Set<Annotation> getAnnotations() {
        return annotations;
    }

    public void setAnnotations(Set<Annotation> annotations) {
        this.annotations = annotations;
    }

    @Override
    public String toString() {
        return "Source_doc{" + "source_doc_id=" + source_doc_id + ", source_doc_text=" + source_doc_text + ", source_doc_name=" + source_doc_name + '}';
    }
    
    
    
    
}
